### PR TITLE
ENH: Scanning probe emulation

### PR DESCRIPTION
**Pull request by pastewka**
This PR emulated "scanning" of line scans with rigid tip

### CODE REVIEW

**Comment by AntoineSIMTEK** [comment]
grafik


The result doesn't make completely sense to me. Shouldn't the kink be where the sphere is touching two flanks of mountains at the same time ?

**Comment by pastewka** [comment]
Isn't that where the cusp is?

**Comment by AntoineSIMTEK** [comment]
Yes sorry. This representation is better:

**Comment by pastewka** [comment]
> Yes sorry. This representation is better: grafik

Yes, exactly!

**Comment by pastewka** [comment]
Hi @AntoineSIMTEK - can this be merged?

**Comment by AntoineSIMTEK** [comment]
Yes I was just waiting on the tests to pas

**Review by AntoineSIMTEK — APPROVED** [review]

**Pull request merged**
